### ISSUE TITLE
Could u explain the parameters in detail?

### ISSUE THREAD

**Issue by hacql2004** [GODqinbin/DPBoost#1]
Hi, thanks for your sharing! 
Follow your instruction, I've run your demo code(exp_run.py) successfully.
But I still get confused of some parameters(list in the below image) in it. Could you explain them more specifically?
Thanks!
![image](https://user-images.githubusercontent.com/21165759/74817874-9cabcc00-5338-11ea-80a7-a309aa5711a1.png)

**Comment by hacql2004** [comment]
Here is the result of your demo.
![image](https://user-images.githubusercontent.com/21165759/74821194-2e6a0800-533e-11ea-8930-d76b23331f9e.png)
I notice that the rmse turns smaller along with the larger value of para:total_budget([1, 2, 4, 6, 8, 10]). Does this para represent the num of parties in FL system? If so, in my view, the rmse should turn larger since the more parties the lower accurancy. Could u help me to figure out it? Thanks.

**Comment by QinbinLi** [comment]
Hi @hacql2004 ,

The explanation of some parameters is available in the Parameter section [here](https://github.com/GODqinbin/DPBoost). The other parameters are used for our previous testing and may not be useful for you. We may delete them in the future.

The total_budget is the total privacy budget (\epsilon in differential privacy). If the privacy budget is bigger, the privacy level is lower and the accuracy usually is higher.

**Comment by hacql2004** [comment]
Thanks for your quickly reply. I found here from your AAAI2020 paper "Practical Federated Gradient Boosting Decision Trees". It seems I need to read your "Privacy-Preserving Gradient Boosting Decision Trees" first.
