### ISSUE TITLE
About classification

### ISSUE THREAD

**Issue by chensquan** [GODqinbin/DPBoost#5]
Dear author:
       After reading the paper you have written, I found that you finished the classification task and regression task in paper, but you only share the code of regression task, would you mind share the code of classification task? Thank you.

**Comment by shib0li** [comment]
Same here, can you show case a simple example how to evaluate the classification task. The cv returns the cross-validation rmse. If I want to evaluate the prediction rates, how to I extract the raw prediction or change the params to let the cv returns the evaluations in terms of classification. Thanks

**Comment by QinbinLi** [comment]
Hi @chensquan  and @shib0li ,

To run on the classification tasks, you can set the parameter `'metric': 'binary_error'` and add another parameter `'boost_from_average': False` in params. Then the results should report prediction errors.
